services:

    mongo:
        image: mongo:7
        restart: unless-stopped
        volumes:
            - mongo-data:/data/db
        ports:
            - "27017:27017"

    redis:
        image: redis:7-alpine
        restart: unless-stopped
        volumes:
            - redis-data:/data
        ports:
            - "6379:6379"

    api:
        build: ./Backend
        restart: unless-stopped
        command: node server.js
        env_file:
            - ./Backend/.env
        environment:
            - MONGO_URI=mongodb://mongo:27017/hiregenie
            - REDIS_URL=redis://redis:6379
        ports:
            - "3000:3000"
        depends_on:
            - mongo
            - redis

    worker:
        build: ./Backend
        restart: unless-stopped
        command: node worker.js
        env_file:
            - ./Backend/.env
        environment:
            - MONGO_URI=mongodb://mongo:27017/hiregenie
            - REDIS_URL=redis://redis:6379
        depends_on:
            - mongo
            - redis

volumes:
    mongo-data:
    redis-data:
